### ISSUE TITLE
Pause not working for me in VLC 3.0.3

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [nurupo/vlc-pause-click-plugin#43] opened 2018-08-24 11:57 UTC
It’s the only version I’ve tried it with and I’ve been futzing with it for an hour. 

1. Downloaded & installed the 64-bit version.
https://github.com/nurupo/vlc-pause-click-plugin/releases/download/1.0.0/vlc-3.0-macosx.zip

![1](https://user-images.githubusercontent.com/15519219/44582577-ec670280-a756-11e8-9c6e-b88634eceff4.png)

2. Placed plugin in correct folder.
Path is /Applications/VLC.app/Contents/MacOS/plugins/libpause_click_plugin.dylib.

![2](https://user-images.githubusercontent.com/15519219/44583366-da3a9380-a759-11e8-88e8-372416b231f0.png)

3. Enabled **Ignore double clicks** in Show All>Video>Filters>Pause click.

![3](https://user-images.githubusercontent.com/15519219/44582729-6c8d6800-a757-11e8-91a7-c7a3b6f22a20.png)

4. Enabled **Pause/Play video on mouse click** in Show All>Interface>Control interfaces.

![4](https://user-images.githubusercontent.com/15519219/44583000-5cc25380-a758-11e8-8a96-d7d31fb7c6db.png)

5. Closed VLC.

6. Opened VLC and played video.
Clicked window and nothing happened. Double-clicks activate/deactivate fullscreen.

7. Repeated steps 5&6 multiple times.

8. Disabled/enabled checkboxes in steps 3&4.

9. Repeated steps 5&6.

10. Cussed a lot.

**Comment by nurupo** [comment] 2018-08-25 01:15
You didn't enable the checkbox from [step 4 of Usage section](https://github.com/nurupo/vlc-pause-click-plugin#usage).

**Comment by ThaddeusChristopher** [comment] 2018-09-03 23:12
I'll note that I'm on VLC 3.0.4 64-bit Windows and believe I may also be experiencing this issue (if not, then I apologize ahead of time). 

The following checkboxes are checked as per the instructions: 
- Video >> Filters >> Pause/Play video on mouse click
- Interface >> Control interfaces >> Pause/Play video on mouse click  (text box reads "pause_click")

Left mouse clicks are no-ops with or without "Ignore double clicks".

In VLC's Advanced Preferences, if I check "Only show current" it does indeed display "Pause click" as a sub-node under Filters. 

Restarting VLC (with or without using the --reset-plugins-cache option) does not appear help. Starting VLC with or without admin privileges also does not appear to change matters.

**Comment by nurupo** [comment] 2018-09-03 23:17
@ThaddeusChristopher please open a separate issue, it gets too confusing when there are many people with different issues talking in the same thread.

**Comment by GitTheHellOutaHere** [comment] 2018-09-04 04:54
> You didn't enable the checkbox from step 4 of Usage section.

Couldn’t - it doesn’t exist.

![vlc video prefs](https://user-images.githubusercontent.com/15519219/45010578-3952a080-afc3-11e8-8ac9-14cf972e0f42.png)


OS X 11.1.2
VLC 3.0.4

**Comment by nurupo** [comment] 2018-09-04 06:08
Wow, that's new, no one has ever reported this before. It's also interesting how you get `Show All>Video>Filters>Pause click` tab but no `Pause click` on `Show All>Video>Filters` tab.

I will try re-building the macOS plugin against a newer macOS SDK and against VLC 3.0.4 specifically and report back with a new plugin binary for you to test.

**Comment by nurupo** [comment] 2018-09-04 06:16
>OS X 11.1.2

There is no such macOS version. The latest macOS [seems to be](https://simple.wikipedia.org/wiki/MacOS#Versions) 10.13.

There is [11.1.2 Safari browser version](https://support.apple.com/en-us/HT208934), but I fail to see how a web browser version is relevant here.

**Comment by nurupo** [comment] 2018-09-04 06:46
Do any of these work for you?

1. [`1 - vlc-3.0-macosx.zip`](https://github.com/nurupo/vlc-pause-click-plugin/files/2347446/1.-.vlc-3.0-macosx.zip) - built with xcode9.4 against VLC 3.0.0
2. [`2 - vlc-3.0-macosx.zip`](https://github.com/nurupo/vlc-pause-click-plugin/files/2347448/2.-.vlc-3.0-macosx.zip) - built with xcode9.4 against VLC 3.0.4
3. [`3 - vlc-3.0-macosx.zip`](https://github.com/nurupo/vlc-pause-click-plugin/files/2347450/3.-.vlc-3.0-macosx.zip) - built with xcode7.3 against VLC 3.0.4

I can't test myself as I don't own a macOS system.

**Comment by GitTheHellOutaHere** [comment] 2018-09-04 07:06
> There is no such macOS version. The latest macOS seems to be 10.13.
There is 11.1.2 Safari browser version, but I fail to see how a web browser version is relevant here.

**D’oh!**
I was in a hurry and looked at the Safari _About_ instead of the OS _About_.
They’re only an inch apart. ;-)

I have 10.12.6.
Funny - I actually wrote down that version but then clicked the Safari _About_ and saw something else so wrote that down even though it didn’t sound right.

**Comment by GitTheHellOutaHere** [comment] 2018-09-04 08:14
Now I’m not sure what’s going on.
It’s possible that the reason the setting was missing in the screenshot was because I’d already deleted the original plugin.

Because when I downloaded #2 of your 3 files and installed the plugin, I expected to see a "this file already exists - do you want to replace it?" message. But there was none. So the first plugin was not present in that folder (no wonder the setting didn’t exist).

When I opened VLC after installing the #2 plugin the setting was there. So I decided to test the original plugin. I deleted the new one and installed the old one and the setting DID appear.

But for some strange reason the original plugin always has the same WRONG date and time associated with it each time it’s placed into the folder. The date the file was added should be shown as TODAY, but is shown as 2/10/18 @ 2:10 am in both the Date Added and Date Modified columns. That’s nearly 9 months ago - **weird!**

![vlc1](https://user-images.githubusercontent.com/15519219/45018617-47161f00-afdf-11e8-8f1d-126163a9917b.png)

I deleted it, unzipped the downloaded file again and put the plugin back in the folder. And the same thing happened - same old date and time added.

I think there’s something wrong with that plugin.

Because when I place your #2 plugin in the folder, it goes straight to the top of the column since it was just added, and shows the correct date and time added/modified.

![vlc2](https://user-images.githubusercontent.com/15519219/45018643-509f8700-afdf-11e8-9593-9d3701807c93.png)



Since it appears the setting may have been "missing" because I deleted it at some point (probably because it wasn’t working since I didn’t enable that setting), I apologize for wasting your time!

**Comment by GitTheHellOutaHere** [comment] 2018-09-04 08:15
The instructions say to 
> Extract the archive at /Applications/VLC.app/Contents/MacOS/plugins/video_filter/

But that folder doesn’t exist.
All the plugins are in /Applications/VLC.app/Contents/MacOS/plugins.

I suggest you edit that path to avoid any confusion.

**Comment by nurupo** [comment] 2018-09-04 08:28
>The date the file was added should be shown as TODAY

It's "Date Modified", not "Date Added", so no, the last time the binary was modified is when it was created in February.

**Comment by GitTheHellOutaHere** [comment] 2018-09-04 08:28
Question:

Pause/play video on mouse click isn’t a filter, it’s an interface action and it’s already present in the Control Interfaces menu. Why does this plugin place an action in the Filter menu? 

Is it a necessary workaround because VideoLAN f’d up the way it _should_ work and the way it _used to_ work?


And now there’s a double-click problem. The video does stop/start when the window is clicked, but if two clicks are done too close together the widow resizes. Is there another setting for that?


Also, back to the instructions. Numbers 3 and 4 say to "enable/disable" the checkboxes.
That would leave both boxes unchecked and the plugin disabled, so what’s the point of installing it?

Perhaps you meant disable/enable, or enable/disable/enable? In the end they need to be enabled, right?

**Comment by nurupo** [comment] 2018-09-04 08:28
Oh, I see there is also "Date Added". No idea where that is coming from.

**Comment by GitTheHellOutaHere** [comment] 2018-09-04 08:38
There absolutely is no video folder in there.

This is the path:

![vlc3](https://user-images.githubusercontent.com/15519219/45020046-bd685080-afe2-11e8-8ef2-ddd03bc3f4f4.png)



And as the screenshots show, the folder was sorted in List view by Date Added, not Date modified, for both files.

The old one may have been _created_ in Feb. (I figured that), but it should show TODAYS date when I place it in the folder, just like your #2 file does because it was added TODAY.

**Comment by GitTheHellOutaHere** [comment] 2018-09-04 08:41
Yes, the setting works with the original downloaded plugin and also with #2 - I didn’t try 1 & 3.

**Comment by nurupo** [comment] 2018-09-04 08:44
>Pause/play video on mouse click isn’t a filter, it’s an interface action and it’s already present in the Control Interfaces menu. Why does this plugin place an action in the Filter menu?
>Is it a necessary workaround because VideoLAN f’d up the way it should work and the way it used to work?

The plugin actually consists of two sub-plugins. One is video filter, that allows it to catch mouse clicks on the video image. Another is interface, it allows it to control playlist (to pause/play currently playing item). By checking both check boxes you are enabling them both. If any one is disabled, the plugin doesn't work, as it either can't see mouse clicks or can't control the playlist.

It used to be just a video filter plugin in VLC 2.1, but in 2.2 they made it so only interface plugins could control the playlist, so here we are now.

>And now there’s a double-click problem. The video does stop/start when the window is clicked, but if two clicks are done too close together the widow resizes. Is there another setting for that?

Double click fullscreens VLC. There might be an option to disable it somewhere, but I don't know of it.

The only configuration the plugin provides in regards to the double-clicking is whether you want the plugin to ignore double-clicks or not. When ignoring them, the plugin won't pause/play on double-click. When not, the plugin will pause/play and play/pause just as you click, essentially making the video stutter, which annoys users who double-click to fullscreen.

>Also, back to the instructions. Numbers 3 and 4 say to "enable/disable" the checkboxes.
That would leave both boxes unchecked and the plugin disabled, so what’s the point of installing it?

Yeah, that should say just "enable".

**Comment by GitTheHellOutaHere** [comment] 2018-09-04 08:50
Okay, I appreciate the help and again - sorry I wasted so much of your time.

Maybe VideoLan should apologize for fowling things up, which caused you to have to create this plugin in the first place.

But at least we cleared up a few things in the instructions, so maybe it’ll help _someone_ down the line.

**Comment by nurupo** [comment] 2018-09-04 08:53
>There absolutely is no video folder in there.

Alright, good to know. It doesn't really matter where the plugin is at, as long as it's somewhere inside the `plugins` directory and not too dip in the subdirs. Putting it directly in `plugins` directory works on all platforms. The original instructions I wrote in 2014 told to put in into video filter since it was only a video filter plugin back then, so I decided to stick with it. Didn't know that on macOS VLC doesn't have any plugin subdirs.

I will correct the instructions based on all these findings sometime later this week.

**Comment by nurupo** [comment] 2018-09-04 09:07
Btw, note that when the ignoring double-click option is enabled, it delays pausing the video until after "Double click interval" milliseconds pass, so it's a lot less snappy experience. So chose your poison: either get snappy pause but stutter when double-clicking to fullscreen, or get delayed pause but no stutter when double-clicking to fullscreen. I'm very used to the video stuttering when fullscreening in MPC on Windows, so I just keep that checkbox unchecked all the time.

**Comment by nurupo** [comment] 2018-09-04 09:08
I take that the issue is resolved, so I will be closing it. Feel free to re-open if it is not so.

**Closed by nurupo** 2018-09-04 09:08 UTC

**Comment by nurupo** [comment] 2018-09-06 13:11
>Also, back to the instructions. Numbers 3 and 4 say to "enable/disable" the checkboxes.

They don't say "enable/disable" the checkboxes". They say "Enable/Disable the plugin with a checkbox".

**Comment by nurupo** [comment] 2018-09-06 17:12
>That’s the same thing - the final instruction leaves the checkbox DISABLED.

No it doesn't, your English comprehension is probably a tab bad. All it says is "You can enable or disable the plugin with the following checkbox: <where to find the checkbox>". It doesn't say "first check the checkbox and then uncheck it".

**Comment by GitTheHellOutaHere** [comment] 2018-09-06 17:28
These are the instructions which, as I said, instruct the user to "**Enable/Disable the plugin with a checkbox**." That could be construed to mean it should be left unchecked,

Which would leave the checkbox in a DISABLED state.

They don’t say to uncheck and then check the box, which would disable and then re-enable it.

![vlc4](https://user-images.githubusercontent.com/15519219/45174176-ffe68480-b1be-11e8-84ad-15614c312839.png)

**Comment by GitTheHellOutaHere** [comment] 2018-09-06 17:30
BTW, Me speak language good.

Me know the best words! :-)
