### ISSUE TITLE
vlc-pause-click-plugin for freebsd...

### ISSUE THREAD

**Issue by Marietto2008** [nurupo/vlc-pause-click-plugin#82] opened 2021-09-22 22:13 UTC
Hello.

I would like to install the pause click plugin on freebsd. Is there a chance to do that ? Anyway I've found it here :

http://ftp.se.freebsd.org/pub/void-ppc-sources/vlc-pause-click-plugin-1.0.0/

and I tried to compile it on FreeBSD 13R,but it didn't work :

make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 13: Need an operator
make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 14: Need an operator
make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 15: Need an operator
make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 17: Need an operator
make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 18: Missing dependency operator
make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 19: Missing dependency operator
make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 21: Need an operator
make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 23: Need an operator
make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 25: Need an operator
make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 27: Need an operator
make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 28: Missing dependency operator
make: "/usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0/Makefile" line 29: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/marietto/Downloads/vlc-pause-click-plugin-1.0.0

**Comment by nurupo** [comment] 2021-09-23 01:11
You might have to use GNU Make to build it.

**Comment by nurupo** [comment] 2021-09-23 01:43
Sounds like GNU Make is in the `gmake` package on FreeBSD.

Also, instead of using

>Anyway I've found it here :
>http://ftp.se.freebsd.org/pub/void-ppc-sources/vlc-pause-click-plugin-1.0.0/

you can grab the latest tarball at https://github.com/nurupo/vlc-pause-click-plugin/archive/refs/tags/2.2.0.tar.gz

**Comment by nurupo** [comment] 2022-01-15 04:55
Closing the issue assuming that it got resolved, since it's plainly obvious that it was caused by the running a non-gnu make on a makefile with gnuisms.

**Closed by nurupo** 2022-01-15 04:55 UTC
Labels: C-question, R-answered, E-OS-freebsd
