### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by jeremythille** [nurupo/vlc-pause-click-plugin#19] opened 2016-07-20 14:22 UTC
Sorry I'm opening an issue because there's just no way I can make this work.
I have a fresh VLC 2.2.4 32bit installation (Windows 7).

I have followed the install instructions to the letter.
I have downloaded the 2.2.x, Windows, 32bit version of the plugin and extracted the archive in {VLC}/plugins/video_filter/.

I have tried extracting _only_ the content of the vlc-2.2.x+ directory. I have also tried extracting the _whole_ archive in this plugin directory, including the whole archive tree, which doesn't really make sense, but that's the instructions. Whatever I do, nothing shows up in the advanced preferences.

Screenshot :
https://postimg.org/image/3u9cnp9jb/

Of course I have restarted VLC several times, tried uninstalling it, reinstalling is, extracting the plugin in many ways.....  Nothing will show up in the preferences.

Can you _please_ explain how to install this?

**Comment by mstraube** [comment] 2016-07-23 12:14
Just copying `libpause_click_plugin.dll` into `Program Files (x86)/VideoLan/VLC/plugins/video_filter/`

or `Program Files/VideoLan/VLC/plugins/video_filter/` for the 64bit Version

works for me on Windows 10 with VLC 2.2.4. See: http://imgur.com/a/YhDi9

**Comment by nurupo** [comment] 2016-07-24 03:47
> I have also tried extracting the whole archive in this plugin directory, including the whole archive tree

I'm confused. There is just a single `.dll` file in the archive, without any directories. If you are seeing `vlc-2.2.x+` in the archive, you somehow managed to download the archive with contents of this repository, which is not what you need. The links to the right archives are in the [README file](https://github.com/nurupo/vlc-pause-click-plugin/tree/master/vlc-2.2.x%2B#windows).

**Comment by jgt1942** [comment] 2016-10-18 08:24
mstraube I cannot get the darn plugin to work, possibly you can give me a clue.

1. I had the the x32 version of VLC installed. 
2. Using Revo Uninstaller I uninstalled the x32 version
3. I downloaded vlc-2.2.4-win64 and installed it.
4. I also downloaded vlc-3.0.x-64bit-win and per you instructions I copied the libpause_click_plugin.dll file to the C:\Program Files\VideoLAN\VLC\plugins\video_filter folder
5. I started VLC
6. I then opened a "mov" file and when I click on the video image it does not pause
7. I looked at your images and in VLC I clicked Tools > Preferences > All (under Show settings) > Control interfaces and I DO NOT see the Pause/Play video on mouse click
8. I then went to the Video > Filters (In the same advanced Preferences window) and there is no "Pause/Play video on mouse click" thus I assume I did something wrong.

I'm running Win10 x64, VLC vlc-2.2.4-win64 and vlc-3.0.x-64bit-win for the plugin. For me it was super difficult to find the vlc-3.0.x-64bit-win download and finding instructions that I could understand was impossible until I found this thread.

**Comment by nurupo** [comment] 2016-10-19 08:11
@jgt1942 Why are you using a plugging for VLC 3.0.x on a VLC 2.2.4? For VLC 2.2.4 you should be using the plugin for 2.2.x VLC versions, in your case, since you have 64-bit VLC, that would be the vlc-2.2.x-64bit-win.zip download. Try using that and report on the results :)

**Comment by Avalonnyc** [comment] 2016-12-02 20:04
I get the have the 32-bit DLL in C:\Program Files (x86)\VideoLAN\VLC\plugins\video_filter, and I get "Pause/Play video on mouse click"  in Control interfaces.  But mouse click doesn't pause the video.  Any suggestions?

**Comment by nurupo** [comment] 2016-12-02 20:09
@Avalonnyc From your description it sounds like your plugin targets VLC 32bit 2.2.x. In that case, you should also check the second checkbox for "Pause/Play video on mouse click" in Video->Filters, in addition to the one you have already checked in Control interfaces.

**Comment by Avalonnyc** [comment] 2016-12-02 20:41
Thanks nurupo;  checking "Pause/Play video on mouse click" in Video->Filters did it.

**Comment by christinhend95** [comment] 2016-12-20 13:32
Hi nurupo, I've been using the plugin for a long time in 2.2.1 and all is well. However, today I tried using it with VLC 3.0.0, I downloaded the proper file and put it in the right folder, but the plugin does not show up under filters in preferences. What am I doing wrong? Thanks in advance.

**Comment by nurupo** [comment] 2016-12-21 04:36
@christinhend95 could you provide the download link for VLC 3.0.0 so that I could reproduce the issue?

**Comment by christinhend95** [comment] 2016-12-21 07:21
@nurupo  I tried both these versions on different PCs:

https://nightlies.videolan.org/build/win32/vlc-3.0.0-20161220-0251/vlc-3.0.0-20161220-0251-git-win32.7z

https://nightlies.videolan.org/build/win64/vlc-3.0.0-20161220-0441/vlc-3.0.0-20161220-0441-git-win64.7z

Of course, I tested them out with the appropriate plugin for each version.

If you tell me which 3.0.0 version works well with your plugin, I'll get that one though. I don't care which one it is, I just wanna switch to 3.0.0 because I don't like how 2.2.1 and 2.2.4 handle m3u8 streams when it comes to time seeking while that works fine in 3.0.0.

**Comment by nurupo** [comment] 2016-12-21 08:23
>If you tell me which 3.0.0 version works well with your plugin, I'll get that one though.

I have tested it on the latest VLC 3.0.0 from March 2016, but it seems that those binaries are no longer on VLC's ftp.

The thing about VLC 3.0.0 is that this version has not been released yet, it's in active development and it constantly keeps changing, so the version of the plugin I made for 3.0.0 in March doesn't work for it now. I have spent last 3 hours trying to build the plugin against the current VLC development version, but I can't seem to get it cross-compiled. In the past I have been building VLC using tarballs of precompiled dependency libraries provided by the VLC team, but they provide them only for released versions of VLC. The latest tarball of libraries worked fine with the development version of VLC in March, but it no longer works with it anymore. I have to compile all the dependency libraries myself, and there are instructions on how to do that on VLC's wiki, but I keep hitting errors that I don't know how to pass though.

Since VLC 3.0.0 actually stands for "current development progress VLC", it has not been released yet, and any plugin I build against it might not work with the newer revision of it later, not to mention that I'm not even able to build my plugin against it, it might be a good idea to just drop support of this development version and support only released VLC versions.

So yeah, I will be dropping support for VLC 3.0.0 until it's actually released and I'm able to build it.

**Comment by christinhend95** [comment] 2016-12-21 08:59
@nurupo Ok, thanks. I suppose you don't happen to have that March version you tested the plugin on, do you?

**Comment by nurupo** [comment] 2016-12-21 09:06
Nope, don't have it anymore.

**Comment by christinhend95** [comment] 2016-12-22 07:45
@nurupo A quick search on the web did turn up a version released on March 28 after all, and the plugin is indeed recognized and functioning. However, it doesn't seem to work on recorded m3u8 streams, which kind of defeats my purpose as the plugin works just as well with this type of streams on 2.2.1 and 2.2.4, but like I said time seeking isn't as good as it is in 3.0.0 since it won't pick up the running time of the stream. So, I guess I'll stick with 2.2.4.

**Comment by nurupo** [comment] 2016-12-22 07:50
This plugin is for pausing video by clicking on the image of it. If your m3u8 streams are videos, it ought to pause them. It doesn't work with music as there is no video image, so VLC doesn't notify plugins of any mouse clicks made on the video image area.

**Comment by nurupo** [comment] 2016-12-22 07:57
If your m3u8 streams are videos and it does't pause them, but pauses other videos, then something very weird is happening. It should either work for all videos that are pause-able, or not work for all videos at all.

**Comment by christinhend95** [comment] 2016-12-22 09:10
They are m3u8 streams of recorded shows off Ustvnow. While the plugin works fine on these streams in 2.2.1 and 2.2.4, it won't work in 3.0.0. However, I just checked again and it seems to be a general issue with pausing m3u8 streams regardless of the plugin. as I couldn't pause the videos through the toolbar button as well. I even disabled the plugin, and the pause button wouldn't work on those streams. So, it has nothing to do with the plugin, it's basically just the fact that 3.0.0 won't pause those streams at all for some reason.

**Closed** 2017-02-13 07:23 UTC
