### ISSUE TITLE
Audio not pausing on click?

### ISSUE THREAD

**Issue by Atoli** [nurupo/vlc-pause-click-plugin#83] opened 2021-10-03 21:38 UTC
### Is your feature request related to a problem? Please describe

The plugin work with video and only video, if i am listening to audio (MP3/FLAC/etc) the plugin won't pause on click.

### Describe the solution you'd like

I would like to request the plugin to work with audio too.

### Describe alternatives you've considered

I don't think there is a audio pause on click, since i tried google and found no version for audio.

### Additional context

Awesome work of the plugin with video, pauses on click without delay, would be AMAZING to have this for audio too.

**Comment by nurupo** [comment] 2021-10-04 16:10
Sorry, not possible because when playing audio-only files there is no video surface that would detect clicks.

Duplicate of #29.

**Closed** 2021-10-04 16:11 UTC
Labels: C-feature, R-duplicate

**Comment by KeyofBlueS** [comment] 2021-10-05 01:31
A workaround is to just activate visualizations, go to "Audio" > "Visualizations" and select any visualization of your choice (except 3D spectrum).

**Comment by nurupo** [comment] 2021-10-05 09:50
@KeyofBlueS that's actually a great idea, added it to the README. Didn't realize the visualizations loaded video filter plugins.
